// All data in this file is fictional and exists only for the prototype demo.
// Government verification responses are DEMONSTRATION data, not real portal output.

export const DEMO_DATE = '03 Oct 2026'

export const officer = {
  name: 'A. K. Verma',
  designation: 'Deputy Manager (Procurement)',
  email: 'ak.verma@cppd.gov.in',
  employeeId: 'CPPD-PO-2291',
  organization: 'Central Public Procurement Department',
  department: 'IT & Communications Procurement Cell',
}

export const bidderAccount = {
  company: 'Apex Systems Pvt Ltd',
  bidderId: 'BDR-2026-0117',
  representative: 'Neha Kulkarni',
  designation: 'Director, Government Business',
  email: 'tenders@apexsystems.example.in',
  phone: '+91 80 4110 2290',
  gstin: '29ABCDE1234F1Z5',
  pan: 'ABCDE1234F',
  udyam: 'UDYAM-KR-03-0048213',
  cin: 'U72200KA2014PTC074512',
  address: '4th Floor, Prestige Tech Park, Outer Ring Road, Bengaluru 560103',
}

// ---------------------------------------------------------------------------
// Tenders
// ---------------------------------------------------------------------------
export const tenders = [
  {
    id: '1048',
    ref: 'GEM/PROC/2026/1048',
    title: 'Supply of Network Equipment',
    department: 'IT & Communications Procurement Cell',
    value: 24500000,
    publishedOn: '28 Aug 2026',
    deadline: '25 Sep 2026, 15:00',
    bids: 8,
    pendingReviews: 3,
    status: 'Under Evaluation',
    compliance: 'In progress',
    description:
      'Supply, installation and commissioning of managed L2/L3 switches, firewalls and wireless access points across 14 regional offices, with 3-year comprehensive warranty.',
    document: 'Network_Equipment_Tender.pdf',
    documentPages: 64,
  },
  {
    id: '0981',
    ref: 'GEM/PROC/2026/0981',
    title: 'Office IT Equipment',
    department: 'Administration Division',
    value: 8600000,
    publishedOn: '11 Aug 2026',
    deadline: '12 Sep 2026, 15:00',
    bids: 5,
    pendingReviews: 1,
    status: 'Review Required',
    compliance: '4 of 5 assessed',
    description: 'Supply of desktops, laptops, multifunction printers and UPS units for headquarters.',
    document: 'Office_IT_Equipment_Tender.pdf',
    documentPages: 38,
  },
  {
    id: '0873',
    ref: 'GEM/PROC/2026/0873',
    title: 'Security Infrastructure',
    department: 'Estate & Security Division',
    value: 31200000,
    publishedOn: '02 Jul 2026',
    deadline: '05 Aug 2026, 15:00',
    bids: 11,
    pendingReviews: 0,
    status: 'Completed',
    compliance: 'All assessed',
    description: 'CCTV surveillance, access control and perimeter intrusion detection for 6 campuses.',
    document: 'Security_Infrastructure_Tender.pdf',
    documentPages: 92,
  },
  {
    id: '1102',
    ref: 'GEM/PROC/2026/1102',
    title: 'Data Centre UPS Replacement',
    department: 'IT & Communications Procurement Cell',
    value: 12800000,
    publishedOn: '22 Sep 2026',
    deadline: '20 Oct 2026, 15:00',
    bids: 0,
    pendingReviews: 0,
    status: 'Open for Bids',
    compliance: 'Awaiting bids',
    description: 'Replacement of 2 × 200 kVA modular UPS systems with battery banks at the primary data centre.',
    document: 'DC_UPS_Replacement_Tender.pdf',
    documentPages: 41,
  },
  {
    id: '1067',
    ref: 'GEM/PROC/2026/1067',
    title: 'Annual Maintenance of HVAC Systems',
    department: 'Estate & Security Division',
    value: 5400000,
    publishedOn: '05 Sep 2026',
    deadline: '08 Oct 2026, 15:00',
    bids: 3,
    pendingReviews: 0,
    status: 'Open for Bids',
    compliance: 'Awaiting deadline',
    description: 'Comprehensive annual maintenance contract for central HVAC plants at 3 office buildings.',
    document: 'HVAC_AMC_Tender.pdf',
    documentPages: 27,
  },
  {
    id: '0995',
    ref: 'GEM/PROC/2026/0995',
    title: 'Cloud Backup Services (3 Years)',
    department: 'IT & Communications Procurement Cell',
    value: 9750000,
    publishedOn: '14 Aug 2026',
    deadline: '15 Sep 2026, 15:00',
    bids: 6,
    pendingReviews: 2,
    status: 'Under Evaluation',
    compliance: '2 reviews pending',
    description: 'Managed backup-as-a-service with MeitY-empanelled cloud provider, 50 TB initial capacity.',
    document: 'Cloud_Backup_Services_Tender.pdf',
    documentPages: 55,
  },
  {
    id: '0912',
    ref: 'GEM/PROC/2026/0912',
    title: 'Fleet Vehicles on Lease',
    department: 'Administration Division',
    value: 6900000,
    publishedOn: '18 Jul 2026',
    deadline: '21 Aug 2026, 15:00',
    bids: 7,
    pendingReviews: 0,
    status: 'Completed',
    compliance: 'All assessed',
    description: 'Dry lease of 12 sedans and 4 utility vehicles for 36 months.',
    document: 'Fleet_Lease_Tender.pdf',
    documentPages: 33,
  },
]

// ---------------------------------------------------------------------------
// Requirement template extracted from Network_Equipment_Tender.pdf
// ---------------------------------------------------------------------------
export const requirementTemplate = [
  {
    id: 'REQ-001',
    title: 'GST Registration',
    category: 'Mandatory',
    criterion: 'Bidder must hold an active GST registration in its legal name.',
    evidence: 'GST Registration Certificate',
    source: 'GST Portal',
    clause: 'Section 4.1(a), p. 12',
  },
  {
    id: 'REQ-002',
    title: 'Minimum Average Annual Turnover',
    category: 'Mandatory',
    criterion: 'Average annual turnover of the last 3 financial years must be at least ₹50,00,000.',
    threshold: '₹50,00,000',
    evidence: 'Audited Financial Statements / CA Certificate',
    source: 'Document + CA certificate check',
    clause: 'Section 4.1(b), p. 12',
  },
  {
    id: 'REQ-003',
    title: 'Relevant Experience',
    category: 'Mandatory',
    criterion: 'Minimum 3 completed projects of network equipment supply in the last 5 years, each of at least ₹40 lakh.',
    threshold: '3 qualifying projects',
    evidence: 'Experience Certificates / Work Orders',
    source: 'Document review',
    clause: 'Section 4.2, p. 13',
  },
  {
    id: 'REQ-004',
    title: 'Udyam Registration',
    category: 'Applicable',
    criterion: 'MSE bidders claiming purchase preference must hold valid Udyam registration.',
    evidence: 'Udyam Certificate',
    source: 'Udyam Portal',
    clause: 'Section 6.3, p. 21',
  },
  {
    id: 'REQ-005',
    title: 'OEM Authorization',
    category: 'Mandatory',
    criterion: 'Bidder must be the OEM or hold a tender-specific authorization from the OEM.',
    evidence: 'OEM Authorization Letter',
    source: 'Document + OEM registry check',
    clause: 'Section 4.4, p. 14',
  },
  {
    id: 'REQ-006',
    title: 'Local Content',
    category: 'Mandatory',
    criterion: 'Class-I local supplier: local content of at least 50% under the Make in India order.',
    threshold: '50%',
    evidence: 'Local Content Declaration',
    source: 'Declaration + rule engine',
    clause: 'Section 6.1, p. 20',
  },
  {
    id: 'REQ-007',
    title: 'Earnest Money Deposit (EMD)',
    category: 'Mandatory',
    criterion: 'EMD of ₹4,90,000 by bank guarantee or e-payment, unless exempted as MSE.',
    threshold: '₹4,90,000',
    evidence: 'EMD Proof / Exemption Certificate',
    source: 'Bank guarantee verification',
    clause: 'Section 5.2, p. 17',
  },
  {
    id: 'REQ-008',
    title: 'Non-Blacklisting Declaration',
    category: 'Mandatory',
    criterion: 'Bidder must not be debarred or blacklisted by any Central or State government entity.',
    evidence: 'Signed Declaration',
    source: 'Debarment list check',
    clause: 'Section 4.6, p. 15',
  },
  {
    id: 'REQ-009',
    title: 'Income Tax Returns',
    category: 'Mandatory',
    criterion: 'ITRs filed for the last 3 assessment years under the bidder PAN.',
    evidence: 'ITR Acknowledgements',
    source: 'Income Tax Department',
    clause: 'Section 4.1(c), p. 12',
  },
  {
    id: 'REQ-010',
    title: 'ISO 9001 Certification',
    category: 'Optional',
    criterion: 'Valid ISO 9001:2015 quality management certification (carries technical marks).',
    evidence: 'ISO Certificate',
    source: 'Certification body register',
    clause: 'Section 7.2, p. 24',
  },
]

// ---------------------------------------------------------------------------
// Bids for tender 1048
// ---------------------------------------------------------------------------
export const bids = [
  {
    id: 'BID-2026-041',
    tenderId: '1048',
    bidder: 'Apex Systems Pvt Ltd',
    bidderId: 'BDR-2026-0117',
    gstin: '29ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    submitted: '18 Sep 2026, 14:32',
    documents: '7/7',
    compliance: 82,
    risk: 'Medium',
    status: 'Under Review',
    results: {
      'REQ-001': 'Satisfied',
      'REQ-002': 'Satisfied',
      'REQ-003': 'Review Required',
      'REQ-004': 'Satisfied',
      'REQ-005': 'Satisfied',
      'REQ-006': 'Satisfied',
      'REQ-007': 'Satisfied',
      'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied',
      'REQ-010': 'Not Satisfied',
    },
  },
  {
    id: 'BID-2026-042',
    tenderId: '1048',
    bidder: 'TechCore Solutions',
    bidderId: 'BDR-2026-0124',
    gstin: '27FGHIJ5678K1Z2',
    pan: 'FGHIJ5678K',
    submitted: '19 Sep 2026, 11:05',
    documents: '6/7',
    compliance: 71,
    risk: 'High',
    status: 'Action Required',
    results: {
      'REQ-001': 'Satisfied',
      'REQ-002': 'Satisfied',
      'REQ-003': 'Satisfied',
      'REQ-004': 'Not Applicable',
      'REQ-005': 'Not Satisfied',
      'REQ-006': 'Review Required',
      'REQ-007': 'Satisfied',
      'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied',
      'REQ-010': 'Satisfied',
    },
  },
  {
    id: 'BID-2026-043',
    tenderId: '1048',
    bidder: 'Nova Infra Technologies',
    bidderId: 'BDR-2026-0131',
    gstin: '07KLMNO9012P1Z8',
    pan: 'KLMNO9012P',
    submitted: '20 Sep 2026, 16:48',
    documents: '7/7',
    compliance: 96,
    risk: 'Low',
    status: 'Ready for Review',
    results: {
      'REQ-001': 'Satisfied',
      'REQ-002': 'Satisfied',
      'REQ-003': 'Satisfied',
      'REQ-004': 'Satisfied',
      'REQ-005': 'Satisfied',
      'REQ-006': 'Satisfied',
      'REQ-007': 'Satisfied',
      'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied',
      'REQ-010': 'Satisfied',
    },
  },
  {
    id: 'BID-2026-044',
    tenderId: '1048',
    bidder: 'Meridian Netcom LLP',
    bidderId: 'BDR-2026-0138',
    gstin: '33PQRST3456U1Z4',
    pan: 'PQRST3456U',
    submitted: '22 Sep 2026, 10:17',
    documents: '7/7',
    compliance: 88,
    risk: 'Low',
    status: 'Compliant',
    results: {
      'REQ-001': 'Satisfied', 'REQ-002': 'Satisfied', 'REQ-003': 'Satisfied', 'REQ-004': 'Not Applicable',
      'REQ-005': 'Satisfied', 'REQ-006': 'Satisfied', 'REQ-007': 'Satisfied', 'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied', 'REQ-010': 'Not Satisfied',
    },
  },
  {
    id: 'BID-2026-045',
    tenderId: '1048',
    bidder: 'Sahyadri Digital Systems',
    bidderId: 'BDR-2026-0142',
    gstin: '27UVWXY7890Z1Z6',
    pan: 'UVWXY7890Z',
    submitted: '23 Sep 2026, 13:51',
    documents: '5/7',
    compliance: 54,
    risk: 'High',
    status: 'Non-Compliant',
    results: {
      'REQ-001': 'Satisfied', 'REQ-002': 'Not Satisfied', 'REQ-003': 'Not Satisfied', 'REQ-004': 'Satisfied',
      'REQ-005': 'Satisfied', 'REQ-006': 'Review Required', 'REQ-007': 'Satisfied', 'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied', 'REQ-010': 'Not Satisfied',
    },
  },
  {
    id: 'BID-2026-046',
    tenderId: '1048',
    bidder: 'Orbit Communications Ltd',
    bidderId: 'BDR-2026-0149',
    gstin: '19ABCPQ2345R1Z9',
    pan: 'ABCPQ2345R',
    submitted: '24 Sep 2026, 09:40',
    documents: '7/7',
    compliance: 91,
    risk: 'Low',
    status: 'Compliant',
    results: {
      'REQ-001': 'Satisfied', 'REQ-002': 'Satisfied', 'REQ-003': 'Satisfied', 'REQ-004': 'Not Applicable',
      'REQ-005': 'Satisfied', 'REQ-006': 'Satisfied', 'REQ-007': 'Satisfied', 'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied', 'REQ-010': 'Satisfied',
    },
  },
  {
    id: 'BID-2026-047',
    tenderId: '1048',
    bidder: 'Kaveri Tech Integrators',
    bidderId: 'BDR-2026-0153',
    gstin: '29LMNOP6789Q1Z3',
    pan: 'LMNOP6789Q',
    submitted: '24 Sep 2026, 17:22',
    documents: '7/7',
    compliance: 79,
    risk: 'Medium',
    status: 'Under Review',
    results: {
      'REQ-001': 'Satisfied', 'REQ-002': 'Satisfied', 'REQ-003': 'Satisfied', 'REQ-004': 'Satisfied',
      'REQ-005': 'Review Required', 'REQ-006': 'Satisfied', 'REQ-007': 'Satisfied', 'REQ-008': 'Satisfied',
      'REQ-009': 'Review Required', 'REQ-010': 'Not Satisfied',
    },
  },
  {
    id: 'BID-2026-048',
    tenderId: '1048',
    bidder: 'Pinnacle Infotech',
    bidderId: 'BDR-2026-0158',
    gstin: '24RSTUV1234W1Z1',
    pan: 'RSTUV1234W',
    submitted: '25 Sep 2026, 12:09',
    documents: '7/7',
    compliance: 85,
    risk: 'Low',
    status: 'Ready for Review',
    results: {
      'REQ-001': 'Satisfied', 'REQ-002': 'Satisfied', 'REQ-003': 'Satisfied', 'REQ-004': 'Not Applicable',
      'REQ-005': 'Satisfied', 'REQ-006': 'Satisfied', 'REQ-007': 'Satisfied', 'REQ-008': 'Satisfied',
      'REQ-009': 'Satisfied', 'REQ-010': 'Not Satisfied',
    },
  },
]

// ---------------------------------------------------------------------------
// Detailed evidence for BID-2026-041 (Apex). Other bids get generated evidence.
// ---------------------------------------------------------------------------
export const apexEvidence = {
  'REQ-001': {
    documents: ['GST_Registration_Certificate.pdf'],
    extracted: [
      ['GSTIN', '29ABCDE1234F1Z5'],
      ['Legal name', 'Apex Systems Pvt Ltd'],
      ['Registration date', '01 Jul 2017'],
      ['Constitution', 'Private Limited Company'],
    ],
    checks: [
      ['GSTIN status on portal', 'Active', 'ok'],
      ['Legal name match', 'Exact match', 'ok'],
      ['Last return filed', 'GSTR-3B, Aug 2026', 'ok'],
    ],
    finding: 'GST registration is active and the legal name matches the bid exactly.',
    source: 'GST Taxpayer Search',
    checkedAt: '03 Oct 2026, 15:12',
    page: 'p. 1',
  },
  'REQ-002': {
    documents: ['CA_Turnover_Certificate.pdf', 'Audited_Financials_FY2023-26.pdf'],
    extracted: [
      ['FY 2023–24', '₹61.2 Lakh'],
      ['FY 2024–25', '₹72.8 Lakh'],
      ['FY 2025–26', '₹79.4 Lakh'],
      ['CA membership no.', '218734 (UDIN 26218734BKCXQZ4410)'],
    ],
    computed: [
      ['Calculated average', '₹71.13 Lakh'],
      ['Required', '₹50.00 Lakh'],
      ['Margin', '+₹21.13 Lakh (42.3%)'],
    ],
    checks: [
      ['Figures match audited statements', 'Consistent across both documents', 'ok'],
      ['UDIN on CA certificate', 'Format valid', 'ok'],
    ],
    finding: 'Average turnover of ₹71.13 lakh exceeds the ₹50 lakh threshold.',
    source: 'Document extraction + rule engine',
    checkedAt: '03 Oct 2026, 15:14',
    page: 'CA certificate p. 1; Financials pp. 4, 19, 33',
  },
  'REQ-003': {
    documents: [
      'Experience_Cert_BSNL_Karnataka.pdf',
      'Experience_Cert_KSRTC.pdf',
      'Experience_Cert_Mysuru_SmartCity.pdf',
    ],
    extracted: [
      ['Projects submitted', '3'],
      ['BSNL Karnataka circle (2023)', '₹1.42 Cr · switching & routers'],
      ['KSRTC depots (2024)', '₹68.5 Lakh · LAN & Wi-Fi'],
      ['Mysuru Smart City (2025)', '₹52.0 Lakh · scope not stated'],
    ],
    computed: [
      ['Projects clearly matching', '2 of 3'],
      ['Required', '3 qualifying projects'],
    ],
    checks: [
      ['Value ≥ ₹40 lakh', 'All 3 projects', 'ok'],
      ['Completed within 5 years', 'All 3 projects', 'ok'],
      ['Scope is network equipment supply', '2 of 3 confirmed', 'warn'],
    ],
    finding:
      'One certificate (Mysuru Smart City) states the contract value but does not describe the supplied items, so its scope could not be matched to the tender requirement.',
    source: 'Document review',
    checkedAt: '03 Oct 2026, 15:16',
    page: 'Mysuru Smart City certificate p. 1',
    reviewReason:
      'Experience certificate requires manual review because project scope could not be confidently matched to the tender requirement.',
  },
  'REQ-004': {
    documents: ['Udyam_Registration_Certificate.pdf'],
    extracted: [
      ['Udyam number', 'UDYAM-KR-03-0048213'],
      ['Enterprise type', 'Small'],
      ['Major activity', 'Manufacturing & services'],
    ],
    checks: [
      ['Registration on Udyam portal', 'Found, active', 'ok'],
      ['Name match', 'Exact match', 'ok'],
    ],
    finding: 'Valid Udyam registration as a Small enterprise. Eligible for MSE purchase preference.',
    source: 'Udyam Registration Verification',
    checkedAt: '03 Oct 2026, 15:12',
    page: 'p. 1',
  },
  'REQ-005': {
    documents: ['OEM_Authorization_Letter.pdf'],
    extracted: [
      ['OEM', 'Netvance Networks India Pvt Ltd'],
      ['Tender reference', 'GEM/PROC/2026/1048'],
      ['Valid until', '31 Mar 2027'],
      ['Signatory', 'Regional Channel Head (South)'],
    ],
    checks: [
      ['Tender-specific authorization', 'Tender ID quoted in letter', 'ok'],
      ['Validity covers contract period', 'Yes', 'ok'],
    ],
    finding: 'Tender-specific OEM authorization quoting the correct tender reference, valid through the contract period.',
    source: 'Document + OEM registry check',
    checkedAt: '03 Oct 2026, 15:15',
    page: 'p. 1',
  },
  'REQ-006': {
    documents: ['Local_Content_Declaration.pdf'],
    extracted: [
      ['Declared local content', '58%'],
      ['Supplier class claimed', 'Class-I local supplier'],
      ['Place of value addition', 'Bengaluru, Karnataka'],
    ],
    computed: [
      ['Declared', '58%'],
      ['Required', '50%'],
    ],
    checks: [['Declaration signed by authorised signatory', 'Yes', 'ok']],
    finding: 'Declared local content of 58% meets the Class-I threshold of 50%.',
    source: 'Declaration + rule engine',
    checkedAt: '03 Oct 2026, 15:15',
    page: 'p. 2',
  },
  'REQ-007': {
    documents: ['EMD_Bank_Guarantee.pdf'],
    extracted: [
      ['Instrument', 'Bank guarantee'],
      ['Amount', '₹4,90,000'],
      ['Issuing bank', 'State Bank of India, Koramangala'],
      ['Valid until', '25 Mar 2027'],
    ],
    checks: [
      ['Amount ≥ required EMD', 'Exact', 'ok'],
      ['Validity ≥ 45 days beyond bid validity', 'Yes', 'ok'],
    ],
    finding: 'Bank guarantee for the full EMD amount with adequate validity.',
    source: 'Bank guarantee verification',
    checkedAt: '03 Oct 2026, 15:13',
    page: 'p. 1',
  },
  'REQ-008': {
    documents: ['Non_Blacklisting_Declaration.pdf'],
    extracted: [['Declaration date', '17 Sep 2026']],
    checks: [
      ['Central debarment list', 'No match', 'ok'],
      ['GeM suspended sellers list', 'No match', 'ok'],
    ],
    finding: 'No debarment found. Signed declaration on file.',
    source: 'Debarment list check',
    checkedAt: '03 Oct 2026, 15:13',
    page: 'p. 1',
  },
  'REQ-009': {
    documents: ['ITR_Acknowledgements_AY2024-26.pdf'],
    extracted: [
      ['PAN', 'ABCDE1234F'],
      ['AY 2024–25', 'Filed 29 Oct 2024'],
      ['AY 2025–26', 'Filed 30 Oct 2025'],
      ['AY 2026–27', 'Filed 26 Sep 2026'],
    ],
    checks: [
      ['PAN status', 'Valid, linked to company name', 'ok'],
      ['Returns filed for 3 years', 'Yes', 'ok'],
    ],
    finding: 'Income tax returns filed for all three assessment years.',
    source: 'Income Tax Department (PAN verification)',
    checkedAt: '03 Oct 2026, 15:14',
    page: 'pp. 1–3',
  },
  'REQ-010': {
    documents: ['ISO_9001_Certificate.pdf'],
    extracted: [
      ['Standard', 'ISO 9001:2015'],
      ['Certificate no.', 'QMS/IN/22/41187'],
      ['Valid until', '14 Aug 2026'],
    ],
    checks: [['Certificate valid on bid date', 'Expired 14 Aug 2026', 'fail']],
    finding: 'ISO 9001 certificate expired before the bid submission date. Optional requirement, so it affects technical marks only.',
    source: 'Certification body register',
    checkedAt: '03 Oct 2026, 15:16',
    page: 'p. 1',
  },
}

// Source-verification cards shown on the Verification screen
export const verificationSources = {
  'BID-2026-041': [
    {
      key: 'gst',
      name: 'GST',
      source: 'GST Taxpayer Search',
      result: 'Active',
      verdict: 'Match',
      fields: [
        ['Submitted GSTIN', '29ABCDE1234F1Z5'],
        ['Matched legal name', 'Apex Systems Pvt Ltd'],
        ['Registration date', '01 Jul 2017'],
        ['Return filing', 'Regular'],
      ],
      ms: 842,
    },
    {
      key: 'udyam',
      name: 'Udyam',
      source: 'Udyam Registration Verification',
      result: 'Registration found',
      verdict: 'Active',
      fields: [
        ['Udyam number', 'UDYAM-KR-03-0048213'],
        ['Classification', 'Small enterprise'],
        ['Name match', 'Exact'],
      ],
      ms: 1130,
    },
    {
      key: 'mca',
      name: 'MCA',
      source: 'MCA Company Master Data',
      result: 'Company status: Active',
      verdict: 'Match',
      fields: [
        ['CIN', 'U72200KA2014PTC074512'],
        ['Date of incorporation', '11 Jun 2014'],
        ['Registered office', 'Bengaluru, Karnataka'],
      ],
      ms: 1376,
    },
    {
      key: 'pan',
      name: 'PAN / ITR',
      source: 'Income Tax Department',
      result: 'PAN valid',
      verdict: 'Match',
      fields: [
        ['PAN', 'ABCDE1234F'],
        ['Name on PAN', 'APEX SYSTEMS PRIVATE LIMITED'],
        ['ITR filed (last 3 AY)', '3 of 3'],
      ],
      ms: 958,
    },
    {
      key: 'epfo',
      name: 'EPFO',
      source: 'EPFO Establishment Search',
      result: 'Establishment found',
      verdict: 'Active',
      fields: [
        ['Establishment code', 'KRBNG0048213000'],
        ['Last ECR filed', 'Aug 2026'],
      ],
      ms: 1604,
    },
    {
      key: 'debar',
      name: 'Debarment',
      source: 'Central Debarment List',
      result: 'No record found',
      verdict: 'Clear',
      fields: [
        ['Searched by', 'PAN, GSTIN, legal name'],
        ['Lists checked', 'Central list, GeM suspended sellers'],
      ],
      ms: 711,
    },
  ],
}

export const verificationStages = [
  { key: 'analysis', label: 'Document analysis', detail: '11 files, 47 pages classified by document type' },
  { key: 'extraction', label: 'Field extraction', detail: '63 fields extracted (OCR on 4 scanned pages)' },
  { key: 'source', label: 'Source verification', detail: '6 authoritative sources queried' },
  { key: 'rules', label: 'Rule evaluation', detail: '10 tender rules applied, incl. Make in India and MSE preference' },
  { key: 'discrepancy', label: 'Discrepancy check', detail: 'Cross-document consistency: 1 issue found' },
  { key: 'assessment', label: 'Assessment', detail: 'Requirement-wise result and risk level prepared' },
]

// ---------------------------------------------------------------------------
// Activity & audit
// ---------------------------------------------------------------------------
export const recentActivity = [
  { time: '15:42', date: '03 Oct 2026', text: 'GST verification reviewed for BID-2026-041', actor: 'A. K. Verma', tone: 'ok' },
  { time: '15:38', date: '03 Oct 2026', text: 'Compliance assessment generated for BID-2026-041', actor: 'Bid Sahayak Engine', tone: 'info' },
  { time: '15:16', date: '03 Oct 2026', text: 'REQ-003 Relevant Experience marked for manual review', actor: 'Bid Sahayak Engine', tone: 'warn' },
  { time: '14:57', date: '03 Oct 2026', text: 'Bidder documents uploaded for BID-2026-041', actor: 'Apex Systems Pvt Ltd', tone: 'info' },
  { time: '11:20', date: '03 Oct 2026', text: 'OEM authorization not satisfied for BID-2026-042', actor: 'Bid Sahayak Engine', tone: 'fail' },
  { time: '17:05', date: '02 Oct 2026', text: 'Tender GEM/PROC/2026/0873 evaluation closed', actor: 'A. K. Verma', tone: 'ok' },
]

export const auditLog = [
  { ts: '03 Oct 2026 15:42', user: 'Procurement Officer', name: 'A. K. Verma', action: 'Reviewed GST verification', entity: 'BID-2026-041', status: 'Completed' },
  { ts: '03 Oct 2026 15:38', user: 'Bid Sahayak Engine', name: 'System', action: 'Generated compliance assessment', entity: 'BID-2026-041', status: 'Completed' },
  { ts: '03 Oct 2026 15:16', user: 'Bid Sahayak Engine', name: 'System', action: 'Flagged REQ-003 for manual review', entity: 'BID-2026-041', status: 'Review Required' },
  { ts: '03 Oct 2026 15:14', user: 'Bid Sahayak Engine', name: 'System', action: 'Verified PAN and ITR filing (demo source)', entity: 'BID-2026-041', status: 'Completed' },
  { ts: '03 Oct 2026 15:12', user: 'Bid Sahayak Engine', name: 'System', action: 'Queried GST Taxpayer Search (demo source)', entity: 'BID-2026-041', status: 'Completed' },
  { ts: '03 Oct 2026 15:31', user: 'Bidder', name: 'Apex Systems Pvt Ltd', action: 'Uploaded GST Certificate', entity: 'BID-2026-041', status: 'Uploaded' },
  { ts: '03 Oct 2026 11:20', user: 'Bid Sahayak Engine', name: 'System', action: 'OEM authorization not satisfied', entity: 'BID-2026-042', status: 'Failed' },
  { ts: '03 Oct 2026 10:02', user: 'Procurement Officer', name: 'A. K. Verma', action: 'Opened bid evaluation', entity: 'GEM/PROC/2026/1048', status: 'Completed' },
  { ts: '02 Oct 2026 17:05', user: 'Procurement Officer', name: 'A. K. Verma', action: 'Closed evaluation and recorded decision', entity: 'GEM/PROC/2026/0873', status: 'Completed' },
  { ts: '02 Oct 2026 16:40', user: 'Procurement Officer', name: 'A. K. Verma', action: 'Approved compliance', entity: 'BID-2026-031', status: 'Approved' },
  { ts: '02 Oct 2026 12:18', user: 'Bidder', name: 'TechCore Solutions', action: 'Responded to clarification request', entity: 'BID-2026-036', status: 'Completed' },
  { ts: '01 Oct 2026 09:55', user: 'Procurement Officer', name: 'A. K. Verma', action: 'Confirmed tender requirements (10)', entity: 'GEM/PROC/2026/1102', status: 'Completed' },
  { ts: '30 Sep 2026 18:30', user: 'Bid Sahayak Engine', name: 'System', action: 'Extracted requirements from tender document', entity: 'GEM/PROC/2026/1102', status: 'Completed' },
  { ts: '25 Sep 2026 15:00', user: 'Bid Sahayak Engine', name: 'System', action: 'Bid submission closed (8 bids)', entity: 'GEM/PROC/2026/1048', status: 'Completed' },
].sort((a, b) => parseTs(b.ts) - parseTs(a.ts))

function parseTs(ts) {
  return new Date(ts.replace(/(\d{2}) (\w{3}) (\d{4}) (\d{2}:\d{2})/, '$2 $1, $3 $4')).getTime()
}

// ---------------------------------------------------------------------------
// Bidder side
// ---------------------------------------------------------------------------
export const bidderDocumentsTemplate = [
  { key: 'gst', reqId: 'REQ-001', name: 'GST Certificate', status: 'Not uploaded', mandatory: true,
    sample: 'GST_Registration_Certificate.pdf',
    extracted: [['GSTIN', '29ABCDE1234F1Z5'], ['Legal name', 'Apex Systems Pvt Ltd'], ['Registration date', '01 Jul 2017']] },
  { key: 'udyam', reqId: 'REQ-004', name: 'Udyam Certificate', status: 'Verified', mandatory: true, note: 'Required because MSE preference is claimed', file: 'Udyam_Registration_Certificate.pdf',
    extracted: [['Udyam number', 'UDYAM-KR-03-0048213'], ['Enterprise type', 'Small']] },
  { key: 'turnover', reqId: 'REQ-002', name: 'Turnover Certificate', status: 'Under Review', mandatory: true, file: 'CA_Turnover_Certificate.pdf',
    extracted: [['FY 2023–24', '₹61.2 Lakh'], ['FY 2024–25', '₹72.8 Lakh'], ['FY 2025–26', '₹79.4 Lakh']] },
  { key: 'experience', reqId: 'REQ-003', name: 'Experience Certificates', status: 'Verified', mandatory: true, file: '3 files',
    extracted: [['Projects', '3'], ['Total value', '₹2.62 Cr']] },
  { key: 'oem', reqId: 'REQ-005', name: 'OEM Authorization', status: 'Missing', mandatory: true,
    sample: 'OEM_Authorization_Letter.pdf',
    extracted: [['OEM', 'Netvance Networks India Pvt Ltd'], ['Tender reference', 'GEM/PROC/2026/1048'], ['Valid until', '31 Mar 2027']] },
  { key: 'local', reqId: 'REQ-006', name: 'Local Content Declaration', status: 'Uploaded', mandatory: true, file: 'Local_Content_Declaration.pdf',
    extracted: [['Declared local content', '58%'], ['Supplier class', 'Class-I']] },
  { key: 'emd', reqId: 'REQ-007', name: 'EMD Proof', status: 'Uploaded', mandatory: true, file: 'EMD_Bank_Guarantee.pdf',
    extracted: [['Instrument', 'Bank guarantee'], ['Amount', '₹4,90,000']] },
]

export const bidderBids = [
  { tenderId: '1048', tender: 'Supply of Network Equipment', ref: 'GEM/PROC/2026/1048', bidId: 'BID-2026-041', submitted: '18 Sep 2026', documents: '7 / 7', compliance: 82, status: 'Under Verification' },
  { tenderId: '0981', tender: 'Office IT Equipment', ref: 'GEM/PROC/2026/0981', bidId: 'BID-2026-033', submitted: '12 Sep 2026', documents: '6 / 6', compliance: 100, status: 'Submitted' },
  { tenderId: '0995', tender: 'Cloud Backup Services (3 Years)', ref: 'GEM/PROC/2026/0995', bidId: 'BID-2026-029', submitted: '14 Sep 2026', documents: '8 / 8', compliance: 64, status: 'Action Required' },
  { tenderId: '0873', tender: 'Security Infrastructure', ref: 'GEM/PROC/2026/0873', bidId: 'BID-2026-018', submitted: '04 Aug 2026', documents: '9 / 9', compliance: 93, status: 'Compliant' },
]

export const bidderNotifications = [
  { time: '03 Oct 2026, 15:38', text: 'Compliance assessment generated for BID-2026-041. Officer review pending.' },
  { time: '02 Oct 2026, 10:12', text: 'Clarification requested on BID-2026-029: upload the MeitY empanelment letter.' },
  { time: '26 Sep 2026, 09:00', text: 'New tender published: Data Centre UPS Replacement (GEM/PROC/2026/1102).' },
]

// ---------------------------------------------------------------------------
// Reports
// ---------------------------------------------------------------------------
export const reports = {
  complianceDistribution: [
    { label: '<50%', value: 9 },
    { label: '50–69%', value: 21 },
    { label: '70–84%', value: 46 },
    { label: '85–94%', value: 41 },
    { label: '95–100%', value: 26 },
  ],
  failureFrequency: [
    { label: 'Relevant Experience', value: 14 },
    { label: 'OEM Authorization', value: 9 },
    { label: 'Local Content', value: 6 },
    { label: 'ISO Certification', value: 4 },
    { label: 'EMD', value: 2 },
    { label: 'Turnover', value: 2 },
  ],
  monthlyVolume: [
    { label: 'Apr', value: 14 },
    { label: 'May', value: 19 },
    { label: 'Jun', value: 22 },
    { label: 'Jul', value: 27 },
    { label: 'Aug', value: 31 },
    { label: 'Sep', value: 30 },
  ],
}
